insert into bn_asig_type (id, name) values (1,'RCA');
insert into bn_asig_type (id, name) values (2,'CASCO');
insert into bn_asig_type (id, name) values (3,'PAID');
insert into bn_asig_type (id, name) values (4,'IMOBIL');
insert into bn_asig_type (id, name) values (5,'MEDICAL');
insert into bn_asig_type (id, name) values (6,'VIATA');
insert into bn_asig_type (id, name) values (7,'TRAVEL');
insert into bn_asig_type (id, name) values (8,'STORNO');
insert into bn_asig_type (id, name) values (9,'RCP');
insert into bn_asig_type (id, name) values (10,'ROTR');
insert into bn_asig_type (id, name) values (11,'SANATATE');
insert into bn_asig_type (id, name) values (12,'ACCIDENTE');
insert into bn_asig_type (id, name) values (13,'CMR');
commit;