insert into bn_utilizare (id, name) values (1,'Personal');
insert into bn_utilizare (id, name) values (2,'Agricultura');
insert into bn_utilizare (id, name) values (3,'Altele');
insert into bn_utilizare (id, name) values (4,'Ambulanta');
insert into bn_utilizare (id, name) values (5,'Constructii');
insert into bn_utilizare (id, name) values (6,'Curierat');
insert into bn_utilizare (id, name) values (7,'Distributie');
insert into bn_utilizare (id, name) values (8,'Inchiriere');
insert into bn_utilizare (id, name) values (9,'Leasing');
insert into bn_utilizare (id, name) values (10,'Masina de serviciu');
insert into bn_utilizare (id, name) values (11,'Rezident strainatate');
insert into bn_utilizare (id, name) values (12,'Scoala de soferi');
insert into bn_utilizare (id, name) values (13,'Securitate, interventie');
insert into bn_utilizare (id, name) values (14,'Silvicultura');
insert into bn_utilizare (id, name) values (15,'Taxi');
insert into bn_utilizare (id, name) values (16,'Transport International');
insert into bn_utilizare (id, name) values (17,'Transport marfuri');
insert into bn_utilizare (id, name) values (18,'Transport persoane');
insert into bn_utilizare (id, name) values (19,'Transport substante inflamabile');
insert into bn_utilizare (id, name) values (20,'Transport urban de persoane');
commit;
